info:
  contact: {}
paths:
  /v1/customer/query:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data": { "user": { "username": "asong", "nickname":
            "", "avatar": "" }, "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6ImFzb25nIiwiZXhwIjoxNTk2OTAyMzEyLCJpc3MiOiJhc29uZyIsIm5iZiI6MTU5Njg5NDExMn0.uUS1TreZusX-hL3nKOSNYZIeZ_0BGrxWjKI6xdpdO40",
            "expiresAt": 1596902312000 },,"msg":"操作成功"}'
          schema:
            type: string
      summary: Get all user
      tags:
      - Base/v1
swagger: "2.0"
